# Generated by Django 3.2.7 on 2021-09-16 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crimson_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimsonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='essay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimson_server.crimsonuser'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimson_server.crimsonuser'),
        ),
    ]
